//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionOrganisationCongres
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gestionCongresEntities : DbContext
    {
        public gestionCongresEntities()
            : base("name=gestionCongresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activite> Activites { get; set; }
        public virtual DbSet<Congressiste> Congressistes { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Ligue> Ligues { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
    
        public virtual int montantTotal(Nullable<int> idCongressiste, ObjectParameter total)
        {
            var idCongressisteParameter = idCongressiste.HasValue ?
                new ObjectParameter("idCongressiste", idCongressiste) :
                new ObjectParameter("idCongressiste", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("montantTotal", idCongressisteParameter, total);
        }
    
        public virtual int nbPlacesActivite(Nullable<int> uneActivite)
        {
            var uneActiviteParameter = uneActivite.HasValue ?
                new ObjectParameter("uneActivite", uneActivite) :
                new ObjectParameter("uneActivite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nbPlacesActivite", uneActiviteParameter);
        }
    
        public virtual int NbPlacesBySession(Nullable<int> numSession)
        {
            var numSessionParameter = numSession.HasValue ?
                new ObjectParameter("numSession", numSession) :
                new ObjectParameter("numSession", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NbPlacesBySession", numSessionParameter);
        }
    
        public virtual ObjectResult<GetCongressistesDisponiblesByActivite_Result> GetCongressistesDisponiblesByActivite(Nullable<int> idA)
        {
            var idAParameter = idA.HasValue ?
                new ObjectParameter("idA", idA) :
                new ObjectParameter("idA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCongressistesDisponiblesByActivite_Result>("GetCongressistesDisponiblesByActivite", idAParameter);
        }
    
        public virtual ObjectResult<GetCongressistesDisponiblesBySession_Result> GetCongressistesDisponiblesBySession(Nullable<int> idS)
        {
            var idSParameter = idS.HasValue ?
                new ObjectParameter("idS", idS) :
                new ObjectParameter("idS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCongressistesDisponiblesBySession_Result>("GetCongressistesDisponiblesBySession", idSParameter);
        }
    
        public virtual int montantTotal1(Nullable<int> idCongressiste, ObjectParameter total)
        {
            var idCongressisteParameter = idCongressiste.HasValue ?
                new ObjectParameter("idCongressiste", idCongressiste) :
                new ObjectParameter("idCongressiste", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("montantTotal1", idCongressisteParameter, total);
        }
    
        public virtual int nbPlacesActivite1(Nullable<int> uneActivite)
        {
            var uneActiviteParameter = uneActivite.HasValue ?
                new ObjectParameter("uneActivite", uneActivite) :
                new ObjectParameter("uneActivite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nbPlacesActivite1", uneActiviteParameter);
        }
    
        public virtual int NbPlacesBySession1(Nullable<int> numSession)
        {
            var numSessionParameter = numSession.HasValue ?
                new ObjectParameter("numSession", numSession) :
                new ObjectParameter("numSession", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NbPlacesBySession1", numSessionParameter);
        }
    }
}
