//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionOrganisationCongres
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Congressistes = new HashSet<Congressiste>();
        }
    
        public int numSession { get; set; }
        public string theme { get; set; }
        public System.TimeSpan heureDebut { get; set; }
        public System.DateTime date { get; set; }
        public int nbPlacesMax { get; set; }
        public decimal prix { get; set; }
        public string nomPresident { get; set; }
        public int idSalle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congressiste> Congressistes { get; set; }
    }
}
